import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import {
  calcShirtOrder,
  calcPrintOrder,
  calcConsultationOrder,
  buildLivePrices,
} from '@/lib/pricing'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const { order_id } = await request.json()
  if (!order_id) return NextResponse.json({ error: 'order_id required' }, { status: 400 })

  // Fetch the order
  const { data: order, error: orderErr } = await supabase
    .from('orders')
    .select('*')
    .eq('id', order_id)
    .single()

  if (orderErr || !order) return NextResponse.json({ error: 'Order not found' }, { status: 404 })

  const config = order.configuration ?? {}

  // Fetch live supplier prices from DB
  const { data: priceRows } = await supabase.from('price_configs').select('id, value_cents')
  const prices = buildLivePrices(priceRows ?? [])

  // Calculate pricing based on product type
  let result
  if (order.product_type === 'shirt') {
    result = calcShirtOrder(config, prices)
  } else if (order.product_type === '3d_print') {
    result = calcPrintOrder(config, prices)
  } else {
    result = calcConsultationOrder(config)
  }

  // Build line items
  const lineItems = result.priceCents > 0
    ? [{
        id: crypto.randomUUID(),
        description: result.description,
        quantity: 1,
        unit_price_cents: result.priceCents,
        total_cents: result.priceCents,
      }]
    : [{
        id: crypto.randomUUID(),
        description: result.description || 'Custom project',
        quantity: 1,
        unit_price_cents: 0,
        total_cents: 0,
      }]

  const subtotal = lineItems.reduce((s, i) => s + i.total_cents, 0)
  const taxRate  = 0
  const taxCents = 0
  const total    = subtotal + taxCents

  const internalNotes = [
    'Auto-generated by quote-draft agent.',
    result.notes,
  ].filter(Boolean).join(' ')

  // Create the draft quote
  const service = createServiceClient()
  const { data: quote, error: quoteErr } = await service
    .from('quotes')
    .insert({
      order_id,
      created_by: user.id,
      status: 'draft',
      line_items: lineItems,
      subtotal_cents: subtotal,
      tax_rate: taxRate,
      tax_cents: taxCents,
      total_cents: total,
      currency: 'CAD',
      material_cost_cents: result.costCents,
      internal_notes: internalNotes,
    })
    .select()
    .single()

  if (quoteErr) {
    console.error('quote-draft agent error:', quoteErr)
    return NextResponse.json({ error: 'Failed to create quote' }, { status: 500 })
  }

  return NextResponse.json({ quote_id: quote.id, quote_number: quote.quote_number, notes: result.notes })
}
