import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import {
  calcShirtLineItems,
  calcPrintOrder,
  calcConsultationOrder,
  buildLivePrices,
} from '@/lib/pricing'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const { order_id } = await request.json()
  if (!order_id) return NextResponse.json({ error: 'order_id required' }, { status: 400 })

  const { data: order, error: orderErr } = await supabase
    .from('orders')
    .select('*')
    .eq('id', order_id)
    .single()

  if (orderErr || !order) return NextResponse.json({ error: 'Order not found' }, { status: 404 })

  const config = order.configuration ?? {}

  const { data: priceRows } = await supabase.from('price_configs').select('id, value_cents')
  const prices = buildLivePrices(priceRows ?? [])

  let lineItems: any[]
  let totalCostCents: number
  let notes: string

  if (order.product_type === 'shirt') {
    const { items, dtfDesc, notes: shirtNotes } = calcShirtLineItems(config, prices)
    notes = shirtNotes

    if (items.length === 0) {
      lineItems = [{ id: crypto.randomUUID(), description: 'Custom apparel', quantity: 1, unit_price_cents: 0, total_cents: 0 }]
      totalCostCents = 0
    } else {
      lineItems = items.map(item => ({
        id: crypto.randomUUID(),
        description: item.description,
        quantity: item.quantity,
        unit_price_cents: item.unitPriceCents,
        total_cents: item.quantity * item.unitPriceCents,
        unit_cost_cents: item.unitCostCents,
      }))
      totalCostCents = items.reduce((s, i) => s + i.unitCostCents * i.quantity, 0)
    }
  } else if (order.product_type === '3d_print') {
    const result = calcPrintOrder(config, prices)
    notes = result.notes
    totalCostCents = result.costCents
    lineItems = [{
      id: crypto.randomUUID(),
      description: result.description,
      quantity: config.quantity ?? 1,
      unit_price_cents: Math.round(result.priceCents / (config.quantity ?? 1)),
      total_cents: result.priceCents,
    }]
  } else {
    const result = calcConsultationOrder(config)
    notes = result.notes
    totalCostCents = 0
    lineItems = [{
      id: crypto.randomUUID(),
      description: result.description || 'Custom project',
      quantity: 1,
      unit_price_cents: 0,
      total_cents: 0,
    }]
  }

  const subtotal = lineItems.reduce((s: number, i: any) => s + i.total_cents, 0)

  const internalNotes = ['Auto-generated by quote-draft agent.', notes].filter(Boolean).join(' ')

  const service = createServiceClient()
  const { data: quote, error: quoteErr } = await service
    .from('quotes')
    .insert({
      order_id,
      created_by: user.id,
      status: 'draft',
      line_items: lineItems,
      subtotal_cents: subtotal,
      tax_rate: 0,
      tax_cents: 0,
      total_cents: subtotal,
      currency: 'CAD',
      material_cost_cents: totalCostCents,
      internal_notes: internalNotes,
    })
    .select()
    .single()

  if (quoteErr) {
    console.error('quote-draft agent error:', quoteErr)
    return NextResponse.json({ error: 'Failed to create quote' }, { status: 500 })
  }

  return NextResponse.json({ quote_id: quote.id, quote_number: quote.quote_number, notes })
}
